#!/bin/sh

echo "XXXXXXXXXXXXXXXXXXXXXXXXXXx"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXx"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXx"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXx"
echo "XXXXXXXXXXXXXXXXXXXXXXXXXXx"

nginx &
/bin/sh
/root/main 
echo "AAAAAAAAAAAAAAAAAAAAAAA"

