FROM ubuntu
FROM alpine

WORKDIR /root

# RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.9/main/" > /etc/apk/repositories
# RUN apk update && apk upgrade && rm -fr /var/cache/apk/*

COPY ./PRC /etc/localtime
COPY ./msa .

RUN mkdir /ms
ENTRYPOINT /root/msa
